# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:mn999999999@tcp(127.0.0.1:3306)/mn_gateway?charset=utf8&parseTime=true&loc=Local"
        max_open_conn = 20
        max_idle_conn = 10
        max_conn_life_time = 100